const Employee=[
    {
        image:"https://th.bing.com/th/id/OIP.kqOAJw-BiLdKTr9-LeUYdAAAAA?pid=ImgDet&w=184&h=184&c=7&dpr=1.3",
        id:1,
        name:"Yashrajsinh",
        age:23,
        salary:10000,
    },
    {
        image:"https://th.bing.com/th/id/OIP.kqOAJw-BiLdKTr9-LeUYdAAAAA?pid=ImgDet&w=184&h=184&c=7&dpr=1.3",
        id:2,
        name:"Pruthvi",
        age:20,
        salary:10000,
    },
    {
        image:"https://th.bing.com/th/id/OIP.962oNbok4_w0NRsEVlB0XAAAAA?pid=ImgDet&w=184&h=184&c=7&dpr=1.3",
        id:3,
        name:"Dhaval",
        age:19,
        salary:10000,
    },
    {
        image:"https://th.bing.com/th/id/OIP.c1GunCHzTxq-F2yeFFYNTgHaJQ?pid=ImgDet&w=184&h=230&c=7&dpr=1.3",
        id:4,
        name:"Jaypal",
        age:21,
        salary:10000,
    },
    {
        image:"https://th.bing.com/th/id/OIP.hVNZ4MWaV_eU2vemTVrFmAHaHa?pid=ImgDet&w=184&h=184&c=7&dpr=1.3",
        id:5,
        name:"Nax",
        age:21,
        salary:10000,
    },
    {
        image:"https://th.bing.com/th/id/OIP.v91YBd1n_plYoufA4Fl3awHaHa?pid=ImgDet&w=184&h=184&c=7&dpr=1.3",
        id:6,
        name:"Jigar",
        age:22,
        salary:10000,
    },
]
export default Employee